name: Unit Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  tests-python2:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python2
      - run: pip2.7 install -r requirements-2.txt
      - run: python2 tests.py
  tests-python3:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install requirements
        run: pip3 install -r requirements-3.txt
      - name: run the tests
        run: python3 tests.py 
